### ISSUE TITLE
Mistyped (?) cleanup-stage

### ISSUE THREAD

**Issue by ijo42** [Griefed/docker-Curseforge-Bot#2]
Hello, Griefed

Currently, i rework's Docker build of CurseForge2Discord and I found a lot of really interesting things in this report.

Exploring the Dockerfile `ijo42 branch` i found stranger line.
https://github.com/Griefed/docker-Curseforge-Bot/blob/3f1aaa37782048a7f2587d5bc4b80ac24f964908/Dockerfile#L35
I'm not sure if this is done by accident or if there is a secret meaning.
But I want to remind you that one layer can not affect existing layers

so, **Cleanup stage** must be one layer w/ deps installing

after I tried s6, I'm eager to write something similar in my repo, but thinner

**Comment by Griefed** [comment]
Heyo ijo42,

thanks for opening an issue! :)
That's a good catch, I completely derped out about the layer mechanic of docker. Will be fixed in the ijo42 and main branch. 
Thanks for the report and happy coding with s6!

Cheers,
Griefed
